/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.2-dev at Mon Jan 19 15:55:09 2015. */

#include "address_server.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t address_server_message_network_default = 1u;


const pb_field_t address_server_message_fields[7] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, address_server_message, uid, uid, 0),
    PB_FIELD(  2, ENUM    , OPTIONAL, STATIC  , OTHER, address_server_message, type, uid, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, address_server_message, network, type, &address_server_message_network_default),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, address_server_message, offered_address, network, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, address_server_message, ttl, offered_address, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, address_server_message, ident, ttl, 0),
    PB_LAST_FIELD
};


